// USER TYPES
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAIL = 'ADD_USER_FAIL';
export const GET_USER_ID_SUCCESS = 'GET_USER_ID_SUCCESS';
export const GET_USER_ID_FAIL = 'GET_USER_ID_FAIL';

// CONTACT TYPES
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_FAIL = 'GET_CONTACTS_FAIL';
export const GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS';
export const GET_CONTACT_FAIL = 'GET_CONTACT_FAIL';
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';
export const ADD_CONTACT_FAIL = 'ADD_CONTACT_FAIL';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_FAIL = 'UPDATE_CONTACT_FAIL';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAIL = 'DELETE_CONTACT_FAIL';

// GROUP TYPES

export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAIL = 'CREATE_GROUP_FAIL';
export const EDIT_GROUP_SUCCESS = 'EDIT_GROUP_SUCCESS';
export const EDIT_GROUP_FAIL = 'EDIT_GROUP_FAIL';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_FAIL = 'DELETE_GROUP_FAIL';
export const GET_GROUP_SUCCESS = 'GET_GROUP_SUCCESS';
export const GET_GROUP_FAIL = 'GET_GROUP_FAIL';
export const GET_ALL_GROUPS_FAIL = 'GET_ALL_GROUPS_FAIL';
export const GET_ALL_GROUPS_SUCCESS = 'GET_ALL_GROUPS_SUCCESS';
// GROUP CONTACT TYPES
export const ADD_CONTACT_TO_GROUP_SUCCESS = 'ADD_CONTACT_TO_GROUP_SUCCESS';
export const ADD_CONTACT_TO_GROUP_FAIL = 'ADD_CONTACT_TO_GROUP_FAIL';
export const REMOVE_CONTACT_FROM_GROUP_SUCCESS =
  'REMOVE_CONTACT_FROM_GROUP_SUCCESS';
export const REMOVE_CONTACT_FROM_GROUP_FAIL = 'REMOVE_CONTACT_FROM_GROUP_FAIL';
export const EDIT_CONTACT_IN_GROUP_SUCCESS = 'EDIT_CONTACT_IN_GROUP_SUCCESS';
export const EDIT_CONTACT_IN_GROUP_FAIL = 'EDIT_CONTACT_IN_GROUP_FAIL';
export const GET_GROUPCONTACTS_BY_GROUP_SUCCESS =
  'GET_GROUPCONTACTS_BY_GROUP_SUCCESS';
export const GET_GROUPCONTACTS_BY_GROUP_FAIL =
  'GET_GROUPCONTACTS_BY_GROUP_FAIL';
export const GET_GROUPCONTACTS_SUCCESS = 'GET_GROUPCONTACTS_SUCCESS';
export const GET_GROUPCONTACTS_FAIL = 'GET_GROUPCONTACTS_FAIL';
// RULE TYPES
export const ADD_RULE_SUCCESS = 'ADD_RULE_SUCCESS';
export const ADD_RULE_FAIL = 'ADD_RULE_FAIL';
export const GET_RULES_SUCCESS = 'GET_RULES_SUCCESS';
export const GET_RULES_FAIL = 'GET_RULES_FAIL';
export const GET_RULE_SUCCESS = 'GET_RULE_SUCCESS';
export const GET_RULE_FAIL = 'GET_RULE_FAIL';
export const UPDATE_RULE_SUCCESS = 'UPDATE_RULE_SUCCESS';
export const UPDATE_RULE_FAIL = 'UPDATE_RULE_FAIL';
export const DELETE_RULE_SUCCESS = 'DELETE_RULE_SUCCESS';
export const DELETE_RULE_FAIL = 'DELETE_RULE_FAIL';

// ENGINE TYPES
export const ADD_ENGINE_SUCCESS = 'ADD_ENGINE_SUCCESS';
export const ADD_ENGINE_FAIL = 'ADD_ENGINE_FAIL';
export const GET_ENGINES_SUCCESS = 'GET_ENGINES_SUCCESS';
export const GET_ENGINES_FAIL = 'GET_ENGINES_FAIL';
export const GET_ENGINE_SUCCESS = 'GET_ENGINE_SUCCESS';
export const GET_ENGINE_FAIL = 'GET_ENGINE_FAIL';
export const UPDATE_ENGINE_SUCCESS = 'UPDATE_ENGINE_SUCCESS';
export const UPDATE_ENGINE_FAIL = 'UPDATE_ENGINE_FAIL';
export const DELETE_ENGINE_SUCCESS = 'DELETE_ENGINE_SUCCESS';
export const DELETE_ENGINE_FAIL = 'DELETE_ENGINE_FAIL';

// EMAIL TYPES
export const ADD_EMAIL_HISTORY_SUCCESS = 'ADD_EMAIL_HISTORY_SUCCESS';
export const ADD_EMAIL_HISTORY_FAIL = 'ADD_EMAIL_HISTORY_FAIL';
export const GET_EMAIL_HISTORY_SUCCESS = 'GET_EMAIL_HISTORY_SUCCESS';
export const GET_EMAIL_HISTORY_FAIL = 'GET_EMAIL_HISTORY_FAIL';
export const GET_EMAIL_TOTAL_SUCCESS = 'GET_EMAIL_TOTAL_SUCCESS';
export const GET_EMAIL_TOTAL_FAIL = 'GET_EMAIL_TOTAL_FAIL';
export const GET_EMAILS_BY_CANDIDATE_SUCCESS =
  'GET_EMAILS_BY_CANDIDATE_SUCCESS';
export const GET_EMAILS_BY_CANDIDATE_FAIL = 'GET_EMAILS_BY_CANDIDATE_FAIL';
export const GET_EMAILS_BY_CONTACT_SUCCESS = 'GET_EMAILS_BY_CONTACT_SUCCESS';
export const GET_EMAILS_BY_CONTACT_FAIL = 'GET_EMAILS_BY_CONTACT_FAIL';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
export const SEND_EMAIL_FAIL = 'SEND_EMAIL_FAIL';
